# Generated by Django 5.2 on 2025-04-27 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='series_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Car Series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('generation', models.CharField(max_length=50)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupe'), ('TOURING', 'Touring'), ('GRAN_COUPE', 'Gran Coupe'), ('SUV', 'SUV')], max_length=20)),
                ('engine_options', models.TextField()),
                ('power_range', models.CharField(max_length=100)),
                ('acceleration_0_100', models.CharField(max_length=20)),
                ('top_speed', models.CharField(max_length=20)),
                ('fuel_consumption', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='car_images/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.carseries')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('series', 'model_name', 'generation')},
            },
        ),
    ]
